Use tsx to run the tool locally instead of ts-node
Following 718b9c0c14ba6319ddf6a4db4d55040e995f41ae,
running `yarn run-tool` now produces an error:

    import { DEFAULT_PROJECT_NAMES, DEFAULT_CACHED_REPOSITORIES_DIRECTORY_PATH } from './constants';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at internalCompileFunction (node:internal/vm:73:18)
        at wrapSafe (node:internal/modules/cjs/loader:1153:20)
        at Module._compile (node:internal/modules/cjs/loader:1205:27)
        at Module.m._compile (/Users/elliot/code/metamask/module-lint/node_modules/ts-node/src/index.ts:1455:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/elliot/code/metamask/module-lint/node_modules/ts-node/src/index.ts:1458:12)
        at Module.load (node:internal/modules/cjs/loader:1091:32)
        at Function.Module._load (node:internal/modules/cjs/loader:938:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
        at phase4 (/Users/elliot/code/metamask/module-lint/node_modules/ts-node/src/bin.ts:567:12)

It's unclear why this happens, but `tsx` is faster than `ts-node` and is
a lot less hassle to use.